### ISSUE TITLE
add reoder task

### ISSUE THREAD

**Issue by obar1** [mattmaniak/queuetodo#1]
drag and drop to reorder them

**Comment by mattmaniak** [comment]
The core of this app is to "queue" tasks so it's quite experimental and I do not plan to implement it.

**Comment by mattmaniak** [comment]
I am closing it

**Comment by mattmaniak** [comment]
Closing.

**Comment by mattmaniak** [comment]
Closing.

**Comment by mattmaniak** [comment]
Closing then.
